import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "@rainbow-me/rainbowkit/styles.css";
import { Web3Provider } from "./providers";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <Web3Provider>{children}</Web3Provider>
      </body>
    </html>
  );
}
